DROP TABLE IF EXISTS request_log;
DROP TABLE IF EXISTS PREPAID_CX_PROV_INSTANCES;
DROP TABLE IF EXISTS PREPAID_CX_PROV_INVOCATIONS;
 
CREATE TABLE request_log (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  uri VARCHAR(250) DEFAULT NULL,
  request JSON DEFAULT NULL,
  response JSON DEFAULT NULL,
  created_date TIMESTAMP DEFAULT NULL
);

CREATE TABLE PREPAID_CX_PROV_INSTANCES (
  ID VARCHAR(50) PRIMARY KEY,
  SERVICE_ID VARCHAR(50) DEFAULT NULL,
  START_DATE TIMESTAMP DEFAULT NULL,
  END_DATE TIMESTAMP DEFAULT NULL,
  CAMPAIGN_OFFER_TYPE VARCHAR(20) DEFAULT NULL,
  CAMPAIGN_OFFER_ID INT DEFAULT NULL,
  INPUT_MAPPING VARCHAR(4000) DEFAULT NULL,
  OUTPUT_MAPPING VARCHAR(4000) DEFAULT NULL,
  STATUS VARCHAR(20) DEFAULT NULL,
  CREATED_BY VARCHAR(100) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT NULL,
  LAST_MODIFIED_BY VARCHAR(100) DEFAULT NULL,
  LAST_MODIFIED_DATE TIMESTAMP DEFAULT NULL,
  DELETED_BY VARCHAR(100) DEFAULT NULL,
  DELETED_DATE TIMESTAMP DEFAULT NULL
);

INSERT INTO PREPAID_CX_PROV_INSTANCES VALUES ('inst-id-001', 'service-id-001', null, null, null, null, null, null, 'CREATED', null, null, null, null, null, null); 

CREATE TABLE PREPAID_CX_PROV_INVOCATIONS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  INSTANCE_ID VARCHAR(50) DEFAULT NULL,
  STATUS VARCHAR(20) DEFAULT NULL,
  INPUT VARCHAR(4000) DEFAULT NULL,
  OUTPUT VARCHAR(4000) DEFAULT NULL,
  CREATED_BY VARCHAR(100) DEFAULT NULL,
  CREATED_DATE TIMESTAMP DEFAULT NULL,
  LAST_MODIFIED_BY VARCHAR(100) DEFAULT NULL,
  LAST_MODIFIED_DATE TIMESTAMP DEFAULT NULL,
  DELETED_BY VARCHAR(100) DEFAULT NULL,
  DELETED_DATE TIMESTAMP DEFAULT NULL
);