--UI VERSION 4 START
  ALTER TABLE PREPAID_CX_OFFER_SELECTION
      ADD  SMS_CAMPAIGN_NAME VARCHAR2(100) ;
  ALTER TABLE PREPAID_CX_OFFER_SELECTION
      ADD  PROMO_TYPE VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_SELECTION
      ADD  MESSAGE_TEXT_1 VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_SELECTION
      ADD  MESSAGE_TEXT_2 VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_SELECTION
      ADD  MESSAGE_TEXT_3 VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_SELECTION
      ADD  MESSAGE_TEXT_4 VARCHAR2(50) ;
--UI VERSION 4 END

  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
      ADD  IS_RECURRING_PROVISIONING NUMBER(1) ;
  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
        ADD  SMS_CAMPAIGN_NAME VARCHAR2(100) ;
  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
        ADD  POST_SMS_CAMPAIGN_NAME VARCHAR2(100) ;
  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
        ADD  DYNAMIC_VARIABLE_1 VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
        ADD  DYNAMIC_VARIABLE_2 VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
        ADD  DYNAMIC_VARIABLE_3 VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
        ADD  DYNAMIC_VARIABLE_4 VARCHAR2(50) ;
  ALTER TABLE PREPAID_CX_OFFER_REDEMPTION
        ADD  DYNAMIC_VARIABLE_5 VARCHAR2(50) ;