create or replace PROCEDURE ADV_FILTER_GET_RECORD_COUNT 
(
  IN_SQL_QUERY IN CLOB 
, OUT_RECORD_COUNT OUT NUMBER
) AS 
BEGIN
    BEGIN
        EXECUTE IMMEDIATE IN_SQL_QUERY INTO OUT_RECORD_COUNT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            OUT_RECORD_COUNT := 0;
        WHEN OTHERS THEN
            OUT_RECORD_COUNT := -1;
    END;
        
END ADV_FILTER_GET_RECORD_COUNT;