curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerBucket'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/bucketDetail?bucketId=OMS|261'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerCampaign?offerId=OMS%7C261'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerDetail?bucketOfferId=OMS|261&campaignOfferId=401'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerSelection?instanceId=63483226-49f3-48a2-8720-4f4c47021e32'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerEligibility?instanceId=63483226-49f3-48a2-8720-4f4c47021e32'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerMonitoring?instanceId=63483226-49f3-48a2-8720-4f4c47021e32'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerRedemption?instanceId=63483226-49f3-48a2-8720-4f4c47021e32'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/offerEventCondition?instanceId=63483226-49f3-48a2-8720-4f4c47021e32'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/listProgram'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/listCountry'

curl -X GET --header 'Accept: application/json' 'https://jihefwrkoypnlto6hgcr6lvvxi.apigateway.eu-frankfurt-1.oci.customer-oci.com/cxdev2/data/listOfferType'